[project]
name = "line-paifahsai-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",
    "fastapi[standard]",
    "geoalchemy2>=0.20.0",
    "line-bot-sdk>=3.25.0",
    "psycopg[binary]>=3.3.6",
    "pyngrok>=8.1.2",
    "sqlalchemy[asyncio]>=2.0",
]
